set_temperature:
  description: "Set the target temperature of the climate device."
  fields:
    temperature:
      description: "Target temperature."
      example: 22

set_fan_mode:
  description: "Set the fan mode of the climate device."
  fields:
    fan_mode:
      description: "Fan mode to set."
      example: "Auto"

set_hvac_mode:
  description: "Set the operating mode of the climate device."
  fields:
    hvac_mode:
      description: "Operating mode to set."
      example: "cool"
