fcu_temp_upd:
  description: "Update fan coil unit settings"
  fields:
    device_name:
      description: "Name of the fan coil unit (e.g., fcu1)"
      example: "fcu1"
    temperature:
      description: "Target temperature"
      example: 22
    mode:
      description: "HVAC mode (off, heat, cool, fan_only)"
      example: "heat"
    fan_speed:
      description: "Fan speed (low, medium, high, auto)"
      example: "auto"